"""Add screening_sessions table

Revision ID: 2c9e0820b45e
Revises: 0fdc8e80db53
Create Date: 2026-08-17 23:31:53.533478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9e0820b45e'
down_revision: Union[str, Sequence[str], None] = '0fdc8e80db53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_sessions_email'), 'screening_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_screening_sessions_id'), 'screening_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_sessions_id'), table_name='screening_sessions')
    op.drop_index(op.f('ix_screening_sessions_email'), table_name='screening_sessions')
    op.drop_table('screening_sessions')
    # ### end Alembic commands ###
