"""
One-time generator for app/data/skills_taxonomy.json.

Builds a curated skill taxonomy (canonical name + aliases + category) covering
programming languages, frameworks, data/ML, cloud & devops, databases, testing,
mobile, design, security, business/soft skills, and more.

Run: python scripts/build_taxonomy.py
"""
import json
import os

# Each entry: canonical name -> (category, [aliases])
# Aliases should be lowercase-normalized variants, abbreviations, or common
# misspellings that resume text might contain. The canonical name itself is
# always matched too, so it does not need to be repeated in aliases.
RAW = {
    # ---------------- Programming Languages ----------------
    "Python": ("language", ["py"]),
    "JavaScript": ("language", ["js", "ecmascript"]),
    "TypeScript": ("language", ["ts"]),
    "Java": ("language", []),
    "C": ("language", ["c programming"]),
    "C++": ("language", ["cpp", "c plus plus"]),
    "C#": ("language", ["csharp", "c sharp"]),
    "Go": ("language", ["golang"]),
    "Rust": ("language", []),
    "Ruby": ("language", []),
    "PHP": ("language", []),
    "Swift": ("language", []),
    "Kotlin": ("language", []),
    "Objective-C": ("language", ["objective c", "objc"]),
    "Scala": ("language", []),
    "R": ("language", ["r language", "r programming"]),
    "MATLAB": ("language", []),
    "Perl": ("language", []),
    "Haskell": ("language", []),
    "Elixir": ("language", []),
    "Erlang": ("language", []),
    "Clojure": ("language", []),
    "Lua": ("language", []),
    "Dart": ("language", []),
    "Julia": ("language", []),
    "Shell Scripting": ("language", ["bash", "shell", "sh scripting", "zsh"]),
    "PowerShell": ("language", ["ps1"]),
    "SQL": ("language", []),
    "PL/SQL": ("language", ["plsql"]),
    "T-SQL": ("language", ["tsql", "transact-sql"]),
    "COBOL": ("language", []),
    "Fortran": ("language", []),
    "Assembly": ("language", ["asm"]),
    "VB.NET": ("language", ["visual basic .net"]),
    "Visual Basic": ("language", ["vb"]),
    "Groovy": ("language", []),
    "Solidity": ("language", []),
    "F#": ("language", ["fsharp"]),
    "Scheme": ("language", []),
    "Prolog": ("language", []),
    "Ada": ("language", []),
    "Delphi": ("language", []),
    "ABAP": ("language", []),
    "HTML": ("language", ["html5"]),
    "CSS": ("language", ["css3"]),
    "XML": ("language", []),
    "YAML": ("language", []),
    "JSON": ("language", []),

    # ---------------- Frontend Frameworks/Libraries ----------------
    "React": ("frontend", ["reactjs", "react.js"]),
    "React Native": ("frontend", ["react-native"]),
    "Angular": ("frontend", ["angularjs", "angular.js"]),
    "Vue.js": ("frontend", ["vue", "vuejs"]),
    "Svelte": ("frontend", ["sveltejs"]),
    "Next.js": ("frontend", ["nextjs", "next js"]),
    "Nuxt.js": ("frontend", ["nuxtjs", "nuxt"]),
    "Redux": ("frontend", []),
    "jQuery": ("frontend", []),
    "Bootstrap": ("frontend", []),
    "Tailwind CSS": ("frontend", ["tailwindcss", "tailwind"]),
    "Sass": ("frontend", ["scss"]),
    "Less": ("frontend", []),
    "Webpack": ("frontend", []),
    "Vite": ("frontend", []),
    "Babel": ("frontend", []),
    "Ember.js": ("frontend", ["emberjs"]),
    "Backbone.js": ("frontend", ["backbonejs"]),
    "Material UI": ("frontend", ["mui"]),
    "Ant Design": ("frontend", ["antd"]),
    "D3.js": ("frontend", ["d3js", "d3"]),
    "Three.js": ("frontend", ["threejs"]),
    "WebGL": ("frontend", []),
    "PWA": ("frontend", ["progressive web app"]),
    "Web Components": ("frontend", []),
    "Storybook": ("frontend", []),

    # ---------------- Backend Frameworks ----------------
    "Node.js": ("backend", ["nodejs", "node"]),
    "Express.js": ("backend", ["express", "expressjs"]),
    "NestJS": ("backend", ["nest.js"]),
    "Django": ("backend", []),
    "Flask": ("backend", []),
    "FastAPI": ("backend", ["fast api"]),
    "Spring Boot": ("backend", ["springboot"]),
    "Spring Framework": ("backend", ["spring"]),
    "Ruby on Rails": ("backend", ["rails", "ror"]),
    "Laravel": ("backend", []),
    "Symfony": ("backend", []),
    "ASP.NET": ("backend", ["asp.net core", "aspnet"]),
    ".NET": ("backend", ["dotnet", ".net core", ".net framework"]),
    "GraphQL": ("backend", []),
    "gRPC": ("backend", []),
    "REST API": ("backend", ["rest", "restful", "restful api"]),
    "SOAP": ("backend", []),
    "Microservices": ("backend", ["microservice architecture"]),
    "WebSockets": ("backend", ["websocket"]),
    "Celery": ("backend", []),
    "RabbitMQ": ("backend", []),
    "Apache Kafka": ("backend", ["kafka"]),
    "gin": ("backend", ["gin framework"]),
    "Phoenix Framework": ("backend", ["phoenix"]),

    # ---------------- Databases ----------------
    "MySQL": ("database", []),
    "PostgreSQL": ("database", ["postgres"]),
    "SQLite": ("database", []),
    "Microsoft SQL Server": ("database", ["mssql", "sql server"]),
    "Oracle Database": ("database", ["oracle db", "oracle"]),
    "MongoDB": ("database", ["mongo"]),
    "Redis": ("database", []),
    "Cassandra": ("database", ["apache cassandra"]),
    "DynamoDB": ("database", ["dynamo db"]),
    "Elasticsearch": ("database", ["elastic search"]),
    "Neo4j": ("database", []),
    "CouchDB": ("database", []),
    "Firebase": ("database", ["firestore"]),
    "MariaDB": ("database", []),
    "Snowflake": ("database", []),
    "BigQuery": ("database", ["google bigquery"]),
    "Redshift": ("database", ["amazon redshift"]),
    "InfluxDB": ("database", []),
    "CockroachDB": ("database", []),
    "Supabase": ("database", []),
    "Vector Database": ("database", ["vector db", "vectordb"]),
    "Pinecone": ("database", []),
    "Weaviate": ("database", []),
    "Chroma": ("database", ["chromadb"]),

    # ---------------- Cloud & DevOps ----------------
    "Amazon Web Services": ("cloud", ["aws"]),
    "Microsoft Azure": ("cloud", ["azure"]),
    "Google Cloud Platform": ("cloud", ["gcp", "google cloud"]),
    "Docker": ("devops", []),
    "Kubernetes": ("devops", ["k8s"]),
    "Terraform": ("devops", []),
    "Ansible": ("devops", []),
    "Puppet": ("devops", []),
    "Chef": ("devops", []),
    "Jenkins": ("devops", []),
    "GitHub Actions": ("devops", []),
    "GitLab CI/CD": ("devops", ["gitlab ci"]),
    "CircleCI": ("devops", []),
    "Travis CI": ("devops", []),
    "CI/CD": ("devops", ["continuous integration", "continuous deployment", "continuous delivery"]),
    "Helm": ("devops", []),
    "Prometheus": ("devops", []),
    "Grafana": ("devops", []),
    "Datadog": ("devops", []),
    "New Relic": ("devops", []),
    "Splunk": ("devops", []),
    "ELK Stack": ("devops", ["elk", "elasticsearch logstash kibana"]),
    "Nginx": ("devops", []),
    "Apache HTTP Server": ("devops", ["apache", "apache2"]),
    "Linux Administration": ("devops", ["linux admin", "linux"]),
    "Unix": ("devops", []),
    "Git": ("devops", []),
    "GitHub": ("devops", []),
    "GitLab": ("devops", []),
    "Bitbucket": ("devops", []),
    "SVN": ("devops", ["subversion"]),
    "AWS Lambda": ("devops", ["lambda"]),
    "AWS EC2": ("devops", ["ec2"]),
    "AWS S3": ("devops", ["s3"]),
    "AWS RDS": ("devops", ["rds"]),
    "AWS EKS": ("devops", ["eks"]),
    "AWS CloudFormation": ("devops", ["cloudformation"]),
    "Azure DevOps": ("devops", []),
    "Serverless": ("devops", ["serverless architecture", "serverless framework"]),
    "Vagrant": ("devops", []),
    "Istio": ("devops", []),
    "Site Reliability Engineering": ("devops", ["sre"]),
    "Infrastructure as Code": ("devops", ["iac"]),

    # ---------------- Data Science / ML / AI ----------------
    "Machine Learning": ("ml", ["ml"]),
    "Deep Learning": ("ml", ["dl"]),
    "Natural Language Processing": ("ml", ["nlp"]),
    "Computer Vision": ("ml", ["cv"]),
    "Artificial Intelligence": ("ml", ["ai"]),
    "TensorFlow": ("ml", []),
    "PyTorch": ("ml", []),
    "Keras": ("ml", []),
    "Scikit-learn": ("ml", ["sklearn", "scikit learn"]),
    "Pandas": ("ml", []),
    "NumPy": ("ml", []),
    "SciPy": ("ml", []),
    "Matplotlib": ("ml", []),
    "Seaborn": ("ml", []),
    "XGBoost": ("ml", []),
    "LightGBM": ("ml", []),
    "CatBoost": ("ml", []),
    "Hugging Face": ("ml", ["huggingface", "transformers library"]),
    "Large Language Models": ("ml", ["llm", "llms"]),
    "Generative AI": ("ml", ["genai", "generative artificial intelligence"]),
    "Retrieval Augmented Generation": ("ml", ["rag"]),
    "Prompt Engineering": ("ml", []),
    "LangChain": ("ml", []),
    "OpenAI API": ("ml", ["openai", "gpt"]),
    "Reinforcement Learning": ("ml", ["rl"]),
    "Neural Networks": ("ml", []),
    "Convolutional Neural Networks": ("ml", ["cnn", "cnns"]),
    "Recurrent Neural Networks": ("ml", ["rnn", "rnns"]),
    "Transformer Models": ("ml", ["transformers"]),
    "Data Mining": ("ml", []),
    "Statistical Analysis": ("ml", ["statistics"]),
    "A/B Testing": ("ml", ["ab testing"]),
    "Predictive Modeling": ("ml", []),
    "Time Series Analysis": ("ml", ["time series forecasting"]),
    "Feature Engineering": ("ml", []),
    "Data Visualization": ("ml", []),
    "Tableau": ("ml", []),
    "Power BI": ("ml", ["powerbi"]),
    "Looker": ("ml", []),
    "Qlik": ("ml", ["qlikview", "qlik sense"]),
    "Apache Spark": ("data", ["spark", "pyspark"]),
    "Apache Hadoop": ("data", ["hadoop"]),
    "Apache Hive": ("data", ["hive"]),
    "Apache Airflow": ("data", ["airflow"]),
    "ETL": ("data", ["extract transform load"]),
    "Data Warehousing": ("data", ["data warehouse"]),
    "Data Engineering": ("data", []),
    "Data Modeling": ("data", []),
    "Databricks": ("data", []),
    "dbt": ("data", ["data build tool"]),
    "MLOps": ("data", []),
    "Jupyter": ("data", ["jupyter notebook"]),
    "Google Colab": ("data", ["colab"]),
    "OpenCV": ("data", []),
    "SAS": ("data", []),
    "SPSS": ("data", []),
    "Excel": ("data", ["microsoft excel", "advanced excel"]),
    "VBA": ("data", []),

    # ---------------- Mobile ----------------
    "iOS Development": ("mobile", ["ios"]),
    "Android Development": ("mobile", ["android"]),
    "Flutter": ("mobile", []),
    "Xamarin": ("mobile", []),
    "SwiftUI": ("mobile", []),
    "Jetpack Compose": ("mobile", []),
    "Ionic": ("mobile", []),
    "Cordova": ("mobile", ["apache cordova", "phonegap"]),

    # ---------------- Testing / QA ----------------
    "Unit Testing": ("testing", []),
    "Integration Testing": ("testing", []),
    "Test Automation": ("testing", []),
    "Selenium": ("testing", []),
    "Cypress": ("testing", []),
    "Playwright": ("testing", []),
    "Jest": ("testing", []),
    "Mocha": ("testing", []),
    "Pytest": ("testing", ["py.test"]),
    "JUnit": ("testing", []),
    "TestNG": ("testing", []),
    "Postman": ("testing", []),
    "Appium": ("testing", []),
    "Load Testing": ("testing", []),
    "JMeter": ("testing", ["apache jmeter"]),
    "Cucumber": ("testing", []),
    "Behavior Driven Development": ("testing", ["bdd"]),
    "Test Driven Development": ("testing", ["tdd"]),
    "Quality Assurance": ("testing", ["qa"]),
    "Manual Testing": ("testing", []),
    "Regression Testing": ("testing", []),

    # ---------------- Security ----------------
    "Cybersecurity": ("security", ["cyber security", "information security", "infosec"]),
    "Penetration Testing": ("security", ["pen testing", "pentest", "pentesting"]),
    "Network Security": ("security", []),
    "Application Security": ("security", ["appsec"]),
    "OWASP": ("security", []),
    "SIEM": ("security", []),
    "Vulnerability Assessment": ("security", []),
    "Cryptography": ("security", []),
    "Identity and Access Management": ("security", ["iam"]),
    "OAuth": ("security", ["oauth2"]),
    "SSO": ("security", ["single sign-on"]),
    "Firewalls": ("security", ["firewall"]),
    "SOC 2": ("security", ["soc2"]),
    "ISO 27001": ("security", []),
    "GDPR": ("security", []),
    "HIPAA": ("security", []),
    "Zero Trust Security": ("security", ["zero trust"]),
    "Ethical Hacking": ("security", []),

    # ---------------- Networking / Systems ----------------
    "TCP/IP": ("networking", ["tcp ip"]),
    "DNS": ("networking", []),
    "VPN": ("networking", []),
    "Load Balancing": ("networking", ["load balancer"]),
    "CDN": ("networking", ["content delivery network"]),
    "Network Administration": ("networking", []),
    "VoIP": ("networking", []),
    "SDN": ("networking", ["software defined networking"]),

    # ---------------- Project Management / Methodologies ----------------
    "Agile Methodology": ("project_management", ["agile"]),
    "Scrum": ("project_management", []),
    "Kanban": ("project_management", []),
    "Waterfall Methodology": ("project_management", ["waterfall"]),
    "Jira": ("project_management", []),
    "Confluence": ("project_management", []),
    "Asana": ("project_management", []),
    "Trello": ("project_management", []),
    "Monday.com": ("project_management", ["mondaycom"]),
    "Product Management": ("project_management", []),
    "Project Management Professional": ("project_management", ["pmp"]),
    "Six Sigma": ("project_management", []),
    "Lean Methodology": ("project_management", ["lean"]),
    "Risk Management": ("project_management", []),
    "Stakeholder Management": ("project_management", []),
    "Roadmapping": ("project_management", ["product roadmap"]),
    "Sprint Planning": ("project_management", []),
    "OKRs": ("project_management", ["objectives and key results"]),

    # ---------------- Design ----------------
    "UI/UX Design": ("design", ["ui ux", "ux ui", "user interface design", "user experience design"]),
    "Figma": ("design", []),
    "Sketch": ("design", []),
    "Adobe Photoshop": ("design", ["photoshop"]),
    "Adobe Illustrator": ("design", ["illustrator"]),
    "Adobe XD": ("design", ["xd"]),
    "InVision": ("design", []),
    "Wireframing": ("design", []),
    "Prototyping": ("design", []),
    "Graphic Design": ("design", []),
    "Design Systems": ("design", []),
    "User Research": ("design", []),
    "Accessibility": ("design", ["wcag", "a11y"]),

    # ---------------- Business / CRM / ERP ----------------
    "Salesforce": ("business", []),
    "SAP": ("business", []),
    "Oracle NetSuite": ("business", ["netsuite"]),
    "Microsoft Dynamics 365": ("business", ["dynamics 365", "ms dynamics"]),
    "HubSpot": ("business", []),
    "Zendesk": ("business", []),
    "Google Analytics": ("business", []),
    "SEO": ("business", ["search engine optimization"]),
    "SEM": ("business", ["search engine marketing"]),
    "Digital Marketing": ("business", []),
    "Content Marketing": ("business", []),
    "Email Marketing": ("business", []),
    "Social Media Marketing": ("business", []),
    "Google Ads": ("business", ["adwords"]),
    "Marketo": ("business", []),
    "Financial Modeling": ("business", []),
    "Budgeting": ("business", []),
    "Forecasting": ("business", []),
    "Bookkeeping": ("business", []),
    "QuickBooks": ("business", []),
    "Accounts Payable": ("business", ["ap"]),
    "Accounts Receivable": ("business", ["ar"]),
    "Supply Chain Management": ("business", []),
    "Procurement": ("business", []),
    "Inventory Management": ("business", []),
    "Recruiting": ("business", ["talent acquisition"]),
    "Onboarding": ("business", []),
    "Payroll": ("business", []),
    "Customer Relationship Management": ("business", ["crm"]),

    # ---------------- Soft Skills ----------------
    "Communication": ("soft_skill", ["communication skills", "verbal communication", "written communication"]),
    "Leadership": ("soft_skill", ["leadership skills"]),
    "Teamwork": ("soft_skill", ["team player", "collaboration"]),
    "Problem Solving": ("soft_skill", ["problem-solving"]),
    "Critical Thinking": ("soft_skill", []),
    "Time Management": ("soft_skill", []),
    "Adaptability": ("soft_skill", []),
    "Creativity": ("soft_skill", []),
    "Conflict Resolution": ("soft_skill", []),
    "Negotiation": ("soft_skill", []),
    "Decision Making": ("soft_skill", []),
    "Attention to Detail": ("soft_skill", []),
    "Mentoring": ("soft_skill", ["coaching"]),
    "Public Speaking": ("soft_skill", ["presentation skills"]),
    "Emotional Intelligence": ("soft_skill", ["eq"]),
    "Cross-functional Collaboration": ("soft_skill", ["cross functional collaboration"]),
    "Customer Service": ("soft_skill", []),
    "Analytical Skills": ("soft_skill", []),
    "Organizational Skills": ("soft_skill", []),
    "Multitasking": ("soft_skill", []),
    "Self-motivated": ("soft_skill", ["self motivated"]),
    "Interpersonal Skills": ("soft_skill", []),

    # ---------------- Operating Systems / Misc Tools ----------------
    "Windows Server": ("os", []),
    "macOS": ("os", ["mac os"]),
    "Ubuntu": ("os", []),
    "Red Hat Enterprise Linux": ("os", ["rhel"]),
    "CentOS": ("os", []),
    "Slack": ("tool", []),
    "Microsoft Teams": ("tool", ["ms teams"]),
    "Zoom": ("tool", []),
    "Notion": ("tool", []),
    "Visual Studio Code": ("tool", ["vscode", "vs code"]),
    "IntelliJ IDEA": ("tool", ["intellij"]),
    "Eclipse": ("tool", []),
    "Xcode": ("tool", []),
    "Android Studio": ("tool", []),
    "Postgres Admin": ("tool", ["pgadmin"]),
    "Docker Compose": ("tool", []),
}


def build():
    entries = []
    for canonical, (category, aliases) in RAW.items():
        entries.append({
            "skill": canonical,
            "category": category,
            "aliases": aliases,
        })
    return entries


def main():
    entries = build()
    out_dir = os.path.join(os.path.dirname(__file__), "..", "app", "data")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "skills_taxonomy.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)
    total_terms = sum(1 + len(e["aliases"]) for e in entries)
    print(f"Wrote {len(entries)} canonical skills ({total_terms} total matchable terms) to {out_path}")


if __name__ == "__main__":
    main()
